syn on                      "语法支持

"common conf {{             通用配置
    set ai                      "自动缩进
    set bs=2                    "在insert模式下用退格键删除
    set showmatch               "代码匹配
    set laststatus=2            "总是显示状态行
    set expandtab               "以下三个配置配合使用，设置tab和缩进空格数
    set shiftwidth=4
    set tabstop=4
    set cursorline              "为光标所在行加下划线
    set number                  "显示行号
    set autoread                "文件在Vim之外修改过，自动重新读入

    set ignorecase              "检索时忽略大小写
    set fileencodings=uft-8,gbk "使用utf-8或gbk打开文件
    set hls                     "检索时高亮显示匹配项
    set helplang=cn             "帮助系统设置为中文
    set foldmethod=syntax       "代码折叠
"}}
